version: '3'

services:
  ftp_server:
    image: webdevops/vsftp
    container_name: server
    environment:
      - FTP_USER=alvgomez
      - FTP_PASSWORD=passw
    volumes:
      - ./ftp_server:/img_server
    ports:
      - 20:20 #active mode ftp connection
      - 21:21 #default control for ftp
    networks:
      - ftp_network

  ftp_client:
    image: linuxserver/filezilla:latest
    container_name: client
    environment:
      - CUSTOM_PORT=5000
    volumes:
      - ./ftp_client:/img_client
    ports:
      - 5000:5000
    networks:
      - ftp_network
    restart: unless-stopped 

  attacker:
    build: .
    container_name: attacker
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - 3000:3000
    networks:
      - ftp_network
    restart: unless-stopped

networks:
  ftp_network:
    driver: bridge
